---
- name: Backup FortiGate configuration via SSH
  hosts: localhost
  gather_facts: no
  vars:
    fgt_ip: "192.168.0.188"
    fgt_user: "admin"
    backup_file: "fg_backup_{{ lookup('pipe', 'date +%Y%m%d_%H%M%S') }}.conf"
    sftp_server: "192.168.0.62"
    sftp_user: "root"
    sftp_password: "redhat"
    private_key_file: "/tmp/private_key"  # <-- Set your private key path here
  tasks:
    - name: copy
      copy:
        src: private_key
        dest: /tmp/private_key
    - name: file permission
      ansible.builtin.file:
        path: /tmp/private_key
        mode: '0600'
    - name: Execute FortiGate backup command via SSH (using private key)
      ansible.builtin.shell: |
        ssh -i {{ private_key_file }} -o StrictHostKeyChecking=no {{ fgt_user }}@{{ fgt_ip }} "execute backup config sftp {{ backup_file }} {{ sftp_server }} {{ sftp_user }} {{ sftp_password }}"
      register: backup_result

    - name: Show backup result
      ansible.builtin.debug:
        var: backup_result.stdout
